import express from 'express';
import authRoutes from './auth.routes.js';
import languageRoutes from './language.routes.js';
import mainCategoryRoutes from './mainCategory.routes.js';
import subCategoryRoutes from './subCategory.routes.js';
import companyCategoryRoutes from './companyCategory.routes.js';
import volumeRoutes from './volume.routes.js';
import staffRoutes from './staff.routes.js';
import uploadRoutes from './upload.routes.js';
import godownRoutes from './godown.routes.js';
import godownStaffRoutes from './godownStaff.routes.js';
import customLevelRoutes from './customLevel.routes.js';
import productRoutes from './product.routes.js';
import inventoryRoutes from './inventory.routes.js';
import vendorRoutes from './vendor.routes.js';
import vendorOrderRoutes from './vendorOrder.routes.js';
import purchaseRoutes from './purchase.routes.js';
import settingsRoutes from './settings.routes.js';
import userRoutes from './user.routes.js';
import bannerRoutes from './banner.routes.js';
import orderRoutes from './order.routes.js';
import deliveryBoyRoutes from './delivery-boy.routes.js';
import orderAssignmentRoutes from './order-assignment.routes.js';
import notificationRoutes from './notification.routes.js';
import adminNotificationRoutes from './admin-notification.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import helpSupportRoutes from './helpSupport.routes.js';
import customSaleRoutes from './custom-sale.routes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/languages', languageRoutes);
router.use('/main-categories', mainCategoryRoutes);
router.use('/sub-categories', subCategoryRoutes);
router.use('/company-categories', companyCategoryRoutes);
router.use('/volumes', volumeRoutes);
router.use('/staff', staffRoutes);
router.use('/upload', uploadRoutes);
router.use('/godowns', godownRoutes);
router.use('/godown-staffs', godownStaffRoutes);
router.use('/custom-levels', customLevelRoutes);
router.use('/products', productRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/vendors', vendorRoutes);
router.use('/vendor-orders', vendorOrderRoutes);
router.use('/purchase', purchaseRoutes);
router.use('/settings', settingsRoutes);
router.use('/users', userRoutes);
router.use('/banners', bannerRoutes);
router.use('/orders', orderRoutes);
router.use('/delivery-boys', deliveryBoyRoutes);
router.use('/order-assignments', orderAssignmentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin-notifications', adminNotificationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/help-support', helpSupportRoutes);
router.use('/custom-sales', customSaleRoutes);

export default router;
